<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <IsPackable>false</IsPackable>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="DependencyModules.SourceGenerator" />
        <PackageReference Include="Hardened.Library.SourceGenerator" />
        <PackageReference Include="Hardened.Web.SourceGenerator" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Hardened.Aws.Lambda.Runtime" />
        <PackageReference Include="Hardened.Shared.Testing" />
        <PackageReference Include="Hardened.Shared.Testing.xUnit" />
        <PackageReference Include="Hardened.Templates.RazorBlade" />
        <PackageReference Include="Hardened.Web.Runtime" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="RazorBlade" />
        <PackageReference Include="xunit.v3" />
        <PackageReference Include="xunit.runner.visualstudio">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\LambdaWidgets.Testing\LambdaWidgets.Testing.csproj" />
    </ItemGroup>

</Project>
